#!/bin/sh

# commit-msg hook does:
#	- Apply commit message convention
#		conditionally, warning if skipped
#	- Check semver
#		conditionally, no warning if skipped
#	- Add gerrit changeid
#		conditionally, no warning if skipped
export hookname=$(basename "$0")
~/.git-hooks/hook-main-wrapper "$@"
