#!/bin/sh

# commit-msg hook does:
#	- Apply commit message convention
#		conditionally, warning if skipped
#	- Check semver
#		conditionally, no warning if skipped
#	- Add gerrit changeid
#		conditionally, no warning if skipped
#	- Remove comments for merges
export hookname=$(bn "$0")
~/.git-hooks/_hook-main-wrapper "$@"
