#!/bin/sh

# pre-push hook does:
#	- Abort push if foxtrot merge detected
#	- Abort push if merge recorded as normal commit detected
export hookname=$(bn "$0")
remote="$1"
   url="$2"

while read local_ref local_sha remote_ref remote_sha
do
	~/.git-hooks/_hook-main-wrapper "$1" "$2" "$local_ref" "$local_sha" "$remote_ref" "$remote_sha"
done
