#!/bin/sh

# prepare-commit-msg hook does:
#  - Massage merge commit message
#    - Remove "remote-tracking" from merge commit subject
#    - Uncomment Conflicts section in merge commit body
#  - Explicitly call commit-msg hook for merge commits

echo "hooks/prepare-commit-msg"

# Massage merge commit message
massageMergeCommitMessage() {
	case "$2" in
		merge)
			# Remove "remote-tracking" from merge commit subject
			sed -i '1 s/^Merge remote-tracking branch /Merge branch /w .git/hook.change' "$msg"
			if [ -s .git/hook.change ]; then
				echo " -remove \"remote-tracking\" from merge commit subject"
			fi
			# Uncomment Conflicts section in merge commit body
			sed -i -e '/^# Conflicts:/,/^#$/ s/# \?//w .git/hook.change' -e 's/\t/  /' "$msg"
			if [ -s .git/hook.change ]; then
				echo " -uncomment \"Conflicts:\" section in merge commit body"
			fi
			# clean up
			cleanUp
			;;
		*) ;;
	esac
}

# Explicitly call commit-msg hook for merge commits
applyCommitHook() {
	case "$2" in
		merge)
			echo " -apply 'commit-msg' hook for merge commit"
			~/.git-hooks/commit-msg "$msg" "prepare-commit-msg"
			;;
		*) ;;
	esac
}

# clean up
cleanUp() {
	rm -f .git/hook.change
}


msg="$1"
massageMergeCommitMessage "$@"
applyCommitHook "$@"
