#!/bin/sh

# Internal fn to format messages with 50/72 convention
applyCommitMessageConventionInternal() {
	msg="$1"
	msgbak="$msg".bak
	msgconvention="$msg".convention
	msgText=$(cat "$msg")
	# if msg is empty (blank lines and comments) then exit
	if [[ $(validTextCount "$msgText") -eq 0 ]]; then
		# exit and let git handle abort or continue (--allow-empty-message)
		cleanUp "$msg"
		exit
	fi
	# clean msg to trim lines and remove starting blank lines
	sed 's/ *$//
		/./,$! d' <<< "$msgText" > "$msgbak"
	# subject
	subject=$(head -n 1 "$msgbak")
	if $(egrep -q "^((Merge (((remote-tracking )?branch(es)?)|(commit(s)?)|(tag(s)?)))|(Revert)|(fixup!)) " <<< "$subject")
	then
		echo "  keeping merge/commit/tag/revert/fixup subject as is"
		echo "$subject" > "$msgconvention"
	else
		# remove trailing period
		if [[ "$subject" == *. ]]; then
			echo "  removing trailing period"
			subject=$(sed 's/\.$//' <<< "$subject")
		fi
		# hack: warn if subject >$subjectLen chars
		# with exit, user will have to type message again
		if [ ${#subject} -gt $subjectLen ]; then
			echo -e "  ${Yellow}WARNING:${None} subject should be upto $subjectLen chars"
			# format
			subject=$(fmt -s -w $subjectLen <<< "$subject")
		fi
		echo "$subject" > "$msgconvention"
	fi
	# apply only if body is not empty
	rest=$(tail -n +2 "$msgbak")
	if [[ $(validTextCount "$rest") -ne 0 ]]; then
		# 2nd line should be blank
		bodylineStart=2
		line2=$(head -n 1 <<< "$rest" )
		if [[ $(validTextCount "$line2") -ne 0 ]]; then
			echo "  adding a blank line after subject"
			bodylineStart=1
		fi
		echo "" >> "$msgconvention"
		# body
		body=$(tail -n +"$bodylineStart" <<< "$rest")
		# fmt does not handle '#' properly so filter out
		sed '/^# --* >8 --*$/,$ d
			/^#/ d' <<< "$body" \
			| fmt -s -w $bodyLen >> "$msgconvention"
	else
		echo "" >> "$msgconvention"
	fi
	# put back unified diff and comments by appending
	udiff=$(sed -n '/^# --* >8 --*$/,$ p' <<< "$rest")
	sed '/^# --* >8 --*$/,$ d' <<< "$rest" \
		| sed -n '/^#/ p' >> "$msgconvention"
	echo "$udiff" >> "$msgconvention"
	# copy .convention to msg
	cp "$msgconvention" "$msg"
}

# text count after removing insignificant content
#	blank lines, starting empty lines, unified diff, comments
validText() {
	text="$1"
	# remove blank lines, starting empty lines, unified diff, comments
	sed 's/ *$//
		/./,$! d
		/^# --* >8 --*$/,$ d
		/^#/ d' <<< "$text"
}
# text count after removing spaces (even between words), newlines
validTextCount() {
	text="$1"
	tr -d " \r\n" <<< $(validText "$text") | wc -c
}

# compare files exactly
fileCompare() {
	if cmp --silent "$1" "$2"; then
		# true
		return 0
	else
		# false
		return 1
	fi
}
# compare files as per git significant content
#   exclude comments
fileCompareRelaxed() {
	text1=$(cat "$1")
	text2=$(cat "$2")
	text1=$(validText "$text1")
	text2=$(validText "$text2")
	if [[ "$text1" == "$text2" ]]; then
		# true
		return 0
	else
		# false
		return 1
	fi
}

# Format commit messages with 50/72 convention
subjectLen=50
bodyLen=72
applyCommitMessageConvention() {
	echo " -apply $subjectLen/$bodyLen commit message convention"
	# msg is user edited
	msg="$1"
	# msg.original is copy of msg
	msgoriginal="$msg".original
	# msg.bak is copy of msg
	msgbak="$msg".bak
	# msg.convention is for convention
	msgconvention="$msg".convention
	# clear
	> "$msgbak"
	> "$msgconvention"
	# copy msg to msgoriginal
	cp "$msg" "$msgoriginal"
	editor=$(git config core.editor)
	# read user input below
	exec < /dev/tty
	while true; do
		# for merge commit, by default, the editor is shown after the
		# proposed commit message is created and not before as is for
		# commit. this results in "no change after applying convention"
		# which is not desired. so skip 1st apply convention call.
		if [ -z "$3" ]; then
			applyCommitMessageConventionInternal "$msg"
			if fileCompareRelaxed "$msgconvention" "$msgbak"; then
				# no change after applying convention, return
				echo "  no change after applying convention"
				echo "  done"
				break;
			fi
			echo "  changing message"
		else
			# remove $3 arg
			set --
		fi
		$editor "$msg"
		if fileCompare "$msg" "$msgconvention"; then
			echo "  no manual change"
			# read -p "now what? (*/undo/abort/force/original) " ans
			question=""
			question+="  now what? ("
			question+="${Prompt}*${None}/"
			question+="${Prompt}u${None}ndo/"
			question+="${Prompt}a${None}bort/"
			question+="${Prompt}f${None}orce/"
			question+="${Prompt}o${None}riginal"
			question+=") "
			echo -e -n "$question"
			read -p '' ans
			case $ans in
				[uU] )
					# undo and show
					echo "  undoing";
					cp "$msgbak" "$msg"
					$editor "$msg"
					# if no diff then return
					if fileCompare "$msg" "$msgbak"; then
						echo "  no manual change after undo"
						echo "  done"
						break;
					fi
					;;
				[aA] )
					# abort commit by exit
					echo 1>&2 "  aborting commit";
					cleanUp "$msg"
					exit 1;;
				[fF] )
					# force message
					echo "  forcing message";
					$editor "$msg"
					break;;
				[oO] )
					# original message
					echo "  original message";
					cp "$msgoriginal" "$msg"
					$editor "$msg"
					break;;
				* )
					# all ok, so commit
					echo "  done";
					break;;
			esac
		fi
	done
	cleanUp "$msg"
}

# clean up
cleanUp() {
	msg="$1"
	rm -f "$msg".bak
	rm -f "$msg".convention
	rm -f "$msg".original
}

# apply wrapper
applyCommitMessageConventionWrapper() {
	if [[ $(getConfig "hook.skip-cmc") == "true" ]]; then
		echo -e " -${Yellow}SKIPPING${None} commit-msg-convention: hook.skip-cmc is true"
	else
		# apply convention when not in rebase
		if [ ! -d .git/rebase-merge ] && [ ! -d .git/rebase-apply ]; then
			applyCommitMessageConvention "$@"
		fi
	fi
}


applyCommitMessageConventionWrapper "$@"
