#!/bin/sh

# Remove comments for merges only
# Note: Removing just '#' comments does not work for 'git commit -v'
# so also remove scissor '>8' comments 
removeComments() {
	case "$2" in
		merge)
			if [[ "$GIT_MERGE_AUTOEDIT" == "no" ]]; then
				sed -i '/^# --* >8 --*$/,$ d
					/^#/ d' "$msg"
			fi
			;;
		*) ;;
	esac
}


msg="$1"
removeComments "$@"
