#!/bin/sh

# Remove comments for merges only
# Note: Removing comments does not work for 'git commit -v'
removeComments() {
	case "$2" in
		merge)
			if [[ "$GIT_MERGE_AUTOEDIT" == "no" ]]; then
				sed -i "/^#/ d" "$msg"
			fi
			;;
		*) ;;
	esac
}


msg="$1"
removeComments "$@"
