#!/bin/sh

    remote="$1"
       url="$2"
 local_ref="$3"
 local_sha="$4"
remote_ref="$5"
remote_sha="$6"

z40=0000000000000000000000000000000000000000
if [ "$local_sha" = $z40 ]; then
	# handle delete, do nothing
	:
else
	# ex $local_ref as "refs/heads/dev"
	branch=$(sed 's,refs/heads/,,' <<< $local_ref)
	remoteBranch=$(sed 's,refs/heads/,,' <<< $remote_ref)
	~/.git-hooks/_helpers/foxtrot-merge-detector "$branch" "$remote/$remoteBranch"
	# check exit code and exit if needed
	exitcode=$?
	if [ $exitcode -eq 1 ]; then
		echo 1>&2 "fatal: foxtrot merge detected, aborting push"
		echo 1>&2 "fatal: from '$branch' to '$remoteBranch'"
		exit $exitcode
	elif [ $exitcode -ne 0 ]; then
		# some other error
		exit $exitcode
	fi
fi
