#!/bin/sh

~/.git-hooks/_helpers/foxtrot-merge-detector
# check exit code and exit if needed
exitcode=$?
if [ $exitcode -ne 0 ]; then
	echo -e "  ${Yellow}WARNING:${None} foxtrot merge detected"
	# swallow exit code
fi
