#!/bin/sh

# Add placeholder '#######'
addPlaceholder() {
	# commit: add placeholder
	sed -i '/^# Please enter the commit message for your changes. Lines starting/i '`
		`'#######\n' \
		"$msg"
	# merge commit: with
	#   GIT_MERGE_AUTOEDIT=no
	# Git does not put default text message or any message for a clean
	# merge which can be used as a hook to insert placeholder so
	# just append it at end.
	# avoid inserting placeholder twice
	if ! grep -q '^#######$' "$msg"; then
		# append at eof
		sed -i '$a#######' "$msg"
	fi
}


msg="$1"
addPlaceholder
