#!/bin/sh

# Add placeholder '#######'
addPlaceholder() {
	case "$2" in
		merge)
			# add placeholder
			sed -i '/^# Please enter a commit message to explain why this merge is necessary,$/i '`
				`'#######\n' \
				"$msg"
			;;
		*)
			# commit, *: add placeholder
			sed -i '/^# Please enter the commit message for your changes. Lines starting$/i '`
				`'#######\n' \
				"$msg"
			;;
	esac
}


msg="$1"
addPlaceholder "$@"
