#!/bin/sh

# Massage commit message
massageCommitMessage() {
	# delete default text
	sed -i \
		-e "/^# Please enter the commit message for your changes. Lines starting/ d" \
		-e "/^# with '#' will be ignored, and an empty message aborts the commit./ d" \
		"$msg"
	# add line after branch
	sed -i \
		-e '/^# On branch /a #' \
		-e '/^# HEAD detached at /a #' \
		"$msg"
}


msg="$1"
massageCommitMessage
