#!/bin/sh

# Add instructions to commit message
addInstructions() {
	# Add semver instructions
	if [ -f .git/hooks/check-semver ]; then
		# use '# Please enter' string as a marker to insert the instructions
		sed -i '/^# Please enter/i '`
			`'# Please add semver line in the commit message.\n'`
			`'#+#MAJOR\n#+#MINOR\n#+#PATCH\n' \
			"$msg"
	fi
}


msg="$1"
addInstructions
