#!/bin/sh

# Explicitly call commit-msg hook for merge commits
applyCommitHook() {
	case "$2" in
		merge)
			echo " -apply 'commit-msg' hook for merge commit"
			~/.git-hooks/commit-msg "$msg" "prepare-commit-msg"
			;;
		*) ;;
	esac
}


msg="$1"
applyCommitHook "$@"
