#!/bin/sh

# Explicitly call commit-msg hook for clean merge commits
applyCommitHook() {
	case "$1,$2" in
		".git/MERGE_MSG,merge")
			echo " -apply 'commit-msg' hook for clean merge commit"
			~/.git-hooks/commit-msg "$msg" "$2" "prepare-commit-msg"
			;;
		*) ;;
	esac
}


msg="$1"
applyCommitHook "$@"
